# Generated by Django 2.1.14 on 2019-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0003_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
